# Generated by Django 5.1 on 2024-09-04 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0002_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="content",
            new_name="text",
        ),
    ]
