# Generated by Django 5.1 on 2024-09-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0003_rename_content_message_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date_added",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
