# Generated by Django 5.1 on 2024-09-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0004_alter_message_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date_added",
            field=models.TimeField(auto_created=True),
        ),
    ]
