# Generated by Django 5.1 on 2024-09-12 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0008_group_creater"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="creater",
            new_name="creator",
        ),
    ]
