# Generated by Django 5.1 on 2024-09-09 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_remove_chat_user_chat_user_a_chat_user_b"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="user_a",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="user_b",
        ),
        migrations.AddField(
            model_name="chat",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chat",
            name="users",
            field=models.JSONField(
                default={"users_id": [0]}, verbose_name="chat_users"
            ),
        ),
    ]
