# Generated by Django 5.1 on 2024-09-08 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_remove_chat_user_a_remove_chat_user_b_chat_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="chat.chat",
            ),
            preserve_default=False,
        ),
    ]
