# Generated by Django 5.1 on 2024-09-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_message_chat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="slug",
        ),
        migrations.AddField(
            model_name="chat",
            name="messages",
            field=models.JSONField(
                default={"messages_id": []}, verbose_name="chat_messages"
            ),
        ),
    ]
