# Generated by Django 5.1 on 2024-09-10 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_remove_chat_user_chat_user1_chat_user2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="messages",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="users",
        ),
        migrations.AddField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chat",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chat",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
