# Generated by Django 5.1 on 2024-09-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0012_alter_chat_user1_alter_chat_user2"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="last_message",
            field=models.IntegerField(default=0),
        ),
    ]
