# Generated by Django 3.2.6 on 2024-08-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user_initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to='main.user'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='main.user'),
        ),
    ]
