# Generated by Django 5.1 on 2024-08-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_auto_20240829_1618"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
