# Generated by Django 5.1 on 2024-08-30 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_message_user_alter_user_password_delete_chat_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
