# Generated by Django 5.1 on 2024-09-02 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="avatars",
            old_name="avatar",
            new_name="path",
        ),
    ]
