# Generated by Django 5.1 on 2024-09-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_rename_avatar_avatars_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatars",
            name="path",
            field=models.ImageField(upload_to="static/media/avatars/"),
        ),
    ]
