# Generated by Django 5.1 on 2024-09-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_avatars_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatars",
            name="path",
            field=models.ImageField(
                default="static/media/avatars/default.png",
                upload_to="static/media/avatars/",
            ),
        ),
    ]
