# Generated by Django 5.1 on 2024-09-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_avatars_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Updates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="avatars",
            name="path",
            field=models.ImageField(
                default="static/media/avatars/default.jpg",
                upload_to="static/media/avatars/",
            ),
        ),
    ]
