# Generated by Django 5.1 on 2024-09-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_updates_alter_avatars_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="updates",
            name="title",
            field=models.TextField(default="Новое обновление"),
        ),
        migrations.AlterField(
            model_name="updates",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
