# Generated by Django 5.1.4 on 2025-01-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='path',
            field=models.FilePathField(default='static/modules/', verbose_name='path'),
        ),
    ]
