# Generated by Django 5.1.4 on 2025-01-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_modules_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
