# Generated by Django 5.1.4 on 2025-01-21 00:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_modules_selected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='user',
        ),
        migrations.AddField(
            model_name='modules',
            name='user',
            field=models.ManyToManyField(related_name='modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
