# Generated by Django 5.1.4 on 2025-01-21 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_modules_user_modules_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='user',
        ),
    ]
