# Generated by Django 5.1.4 on 2025-01-21 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_modules_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modules',
            old_name='selected',
            new_name='visible',
        ),
    ]
