# Generated by Django 5.1.4 on 2025-01-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_selected_modules_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='visible_in_public',
            field=models.BooleanField(default=False),
        ),
    ]
