# Generated by Django 5.1.4 on 2025-01-26 22:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_modules_visible_in_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
