# Generated by Django 5.1.4 on 2025-01-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_modules_date_created_alter_modules_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='verificated',
            field=models.BooleanField(default=False, verbose_name='check'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='path',
            field=models.FileField(default='static/modules/default/profile.html', upload_to='static/modules/', verbose_name='path'),
        ),
    ]
