# Generated by Django 5.1.4 on 2025-01-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_modules_verificated_alter_modules_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='path',
            field=models.FileField(default='static/media/modules/default/profile.html', upload_to='static/media/modules/', verbose_name='path'),
        ),
    ]
