# Generated by Django 5.1.4 on 2025-01-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_modules_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modules',
            old_name='user',
            new_name='creator_user',
        ),
    ]
