# Generated by Django 5.1.4 on 2025-01-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_user_modules_creator_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modules',
            old_name='creator_user',
            new_name='user',
        ),
    ]
