# Generated by Django 5.1.4 on 2025-01-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_creator_user_modules_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='visibility_for_others',
            field=models.BooleanField(default=False),
        ),
    ]
