# Generated by Django 5.1.4 on 2025-01-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_addedmodules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='visibility_for_others',
        ),
        migrations.RemoveField(
            model_name='modules',
            name='visible',
        ),
        migrations.RemoveField(
            model_name='modules',
            name='visible_in_public',
        ),
        migrations.AddField(
            model_name='addedmodules',
            name='visibility_for_others',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addedmodules',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addedmodules',
            name='visible_in_public',
            field=models.BooleanField(default=False),
        ),
    ]
