# Generated by Django 5.1.4 on 2025-01-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_modules_visibility_for_others_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addedmodules',
            name='visible_in_public',
        ),
        migrations.AddField(
            model_name='modules',
            name='visible_in_public',
            field=models.BooleanField(default=False),
        ),
    ]
