# Generated by Django 5.1.4 on 2025-01-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_usersupplement'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedmodules',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addedmodules',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
