# Generated by Django 3.2.1 on 2025-02-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_addedmodules_height_addedmodules_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars',
            name='path',
            field=models.ImageField(default='static/media/avatars/default.png', upload_to='static/media/avatars/'),
        ),
        migrations.AlterField(
            model_name='usersupplement',
            name='description',
            field=models.TextField(default='Описание'),
        ),
    ]
